-- MySQL Script generated by MySQL Workbench
-- Thu Jun 13 21:03:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ventadediscos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ventadediscos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ventadediscos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ventadediscos` ;

-- -----------------------------------------------------
-- Table `ventadediscos`.`membresia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventadediscos`.`membresia` (
    `idMembresia` INT NOT NULL AUTO_INCREMENT,
    `tipo` VARCHAR(45) NOT NULL,
    `descuento` DECIMAL(5,2) NOT NULL,
    PRIMARY KEY (`idMembresia`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ventadediscos`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventadediscos`.`usuario` (
    `idUsuario` INT NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(45) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `nombre` VARCHAR(45) NOT NULL,
    `apellido` VARCHAR(45) NOT NULL,
    `Membresia_idMembresia` INT NULL DEFAULT NULL,
    PRIMARY KEY (`idUsuario`),
    UNIQUE INDEX `email` (`email` ASC) VISIBLE,
    INDEX `Membresia_idMembresia` (`Membresia_idMembresia` ASC) VISIBLE,
    CONSTRAINT `usuario_ibfk_1`
        FOREIGN KEY (`Membresia_idMembresia`)
        REFERENCES `ventadediscos`.`membresia` (`idMembresia`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ventadediscos`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventadediscos`.`carrito` (
    `idCarrito` INT NOT NULL AUTO_INCREMENT,
    `Usuario_idUsuario` INT NULL DEFAULT NULL,
    PRIMARY KEY (`idCarrito`),
    INDEX `Usuario_idUsuario` (`Usuario_idUsuario` ASC) VISIBLE,
    CONSTRAINT `carrito_ibfk_1`
        FOREIGN KEY (`Usuario_idUsuario`)
        REFERENCES `ventadediscos`.`usuario` (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ventadediscos`.`genero` 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventadediscos`.`genero` ( 
    `idGenero` INT NOT NULL AUTO_INCREMENT, 
    `tipo` VARCHAR(45) NOT NULL, 
    PRIMARY KEY (`idGenero`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ventadediscos`.`disco`  
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventadediscos`.`disco` (  
    `idDisco` INT NOT NULL AUTO_INCREMENT,  
    `nombre` VARCHAR(45) NOT NULL,  
    `precio` DECIMAL(10,2) NOT NULL, 
    `artista` VARCHAR(45), 
    `anioLanzamiento` INT, 
    `Genero_idGenero` INT NULL DEFAULT NULL,  
    PRIMARY KEY (`idDisco`),  
    INDEX `Genero_idGenero` (`Genero_idGenero` ASC) VISIBLE, 
    CONSTRAINT `disco_ibfk_1`   
        FOREIGN KEY (`Genero_idGenero`)   
        REFERENCES `ventadediscos`.`genero` (`idGenero`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



-- -----------------------------------------------------
-- Table `ventadediscos`.`carrito_has_disco` 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventadediscos`.`carrito_has_disco` ( 
    `Carrito_idCarrito` INT NOT NULL, 
    `Disco_idDisco` INT NOT NULL,  
    PRIMARY KEY (`Carrito_idCarrito`, `Disco_idDisco`),  
    INDEX `Disco_idDisco` (`Disco_idDisco` ASC) VISIBLE,  
    CONSTRAINT `carrito_has_disco_ibfk_1`   
        FOREIGN KEY (`Carrito_idCarrito`)   
        REFERENCES `ventadediscos`.`carrito` (`idCarrito`),  
    CONSTRAINT `carrito_has_disco_ibfk_2`   
        FOREIGN KEY (`Disco_idDisco`)   
        REFERENCES `ventadediscos`.`disco` (`idDisco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ventadediscos`.`compra` 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventadediscos`.`compra` ( 
    `idCompra` INT NOT NULL AUTO_INCREMENT, 
    `Usuario_idUsuario` INT NULL DEFAULT NULL, 
    `Disco_idDisco` INT NULL DEFAULT NULL,  
    `fecha` DATETIME NULL DEFAULT NULL, 
    `total` DECIMAL(10,2) NULL DEFAULT NULL,  
    PRIMARY KEY (`idCompra`),  
    INDEX `Usuario_idUsuario` (`Usuario_idUsuario` ASC) VISIBLE,  
    INDEX `Disco_idDisco` (`Disco_idDisco` ASC) VISIBLE, 
    CONSTRAINT `compra_ibfk_1`   
        FOREIGN KEY (`Usuario_idUsuario`)   
        REFERENCES `ventadediscos`.`usuario` (`idUsuario`),  
    CONSTRAINT `compra_ibfk_2`   
        FOREIGN KEY (`Disco_idDisco`)   
        REFERENCES `ventadediscos`.`disco` (`idDisco`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
